### ISSUE TITLE
Syntax highlighting logic - 4.2.1

### ISSUE THREAD

**Issue by rwilloughby** [gruvbox-material/vscode#10]
The changes you have made to syntax highlighting in the latest update (4.2.1) have made Python code have minimal highlighting.  Way too many elements are defaulting to the source color (#d4be98).  There is no invalid highlighting (that was an issue prior to this update).

I suggest you look at: https://github.com/MagicStack/MagicPython/tree/master/test which will give you the best examples of python code and the correct scopes.  There is also a MagicPython extension which maps to the above.

**Comment by sainnhe** [comment]
Thanks for your suggestion :)

The syntax highlighting logic has been adjusted for the following 2 reasons:

1. Both function and string use green which cannot be distinguished. In the new syntax highlighting logic, yellow is used as the color of string in some languages.
2. There are too many colors in the original syntax highlighting logic. If everything is special, then nothing is special. So in the new syntax highlighting logic, **the color of variable name and property has been removed**.

Python has been optimized before I release v4.2.1, and I think the necessary scopes are already highlighted.

If you think there are other scopes that need to be highlighted, you can open a PR or tell me which scopes they are. Proceed as follows:

1. Clone this repo and open the folder using vscode.
2. Press `F5` to enter debug mode.
3. Press `Ctrl` + `Shift` + `P` and input `Inspect TM Scopes`.
4. Navigate a python project and you will see the scope of current code.

![demo](https://user-images.githubusercontent.com/37491630/72768077-144ee400-3c31-11ea-92b1-e1b323741f96.png)

In this example, the scope is `variable.parameter.function.language.python`.

If you want to open a PR, you can fork this repo and edit theme files in `themes/*`.

To use white in `variable.parameter.function.language.python`, you can add code like this:

```json
        {
            "name": "Python white",
            "scope": "variable.parameter.function.language.python",
            "settings": {
                "foreground": "#d4be98"
            }
        },
```

**Comment by sainnhe** [comment]
Closed.
