### ISSUE TITLE
[DISCUSS] Syntax Higlighting Logic

### ISSUE THREAD

**Issue by GulajavaMinistudio** [gruvbox-material/vscode#9]
Lets discuss about syntax highlighting logic , scope that need for fixing highlighting, window border design , and many more.

I dont know about logic in syntax highlighting. But maybe i can discuss about bordered panel in this theme. Maybe we can add some high contrast version, without bordering. As we can see in other theme as well.

**Comment by sainnhe** [comment]
I'm working on the `refactor` branch, the syntax highlighting logic is as follows:

- Red: keyword
- Orange: storage, modifier, operator
- Yellow: type, string escape
- Green: string, number, boolean
- Aqua: preproccess, modules, annotation
- Blue: function, methods
- Purple: constant, special identifier(this, self, etc), class, macro
- White: variable name, property, member

![demo](https://user-images.githubusercontent.com/37491630/72487721-e2f9a100-3849-11ea-99d1-305c5e43715e.png)

**Comment by GulajavaMinistudio** [comment]
Looks great composition.
But, for variable type such as string, number, boolean . Can it make different color ? maybe green for string, blue or purple for boolean and number ? 

And what color for "import" and "export" ? green dark or bright green ?

**Comment by sainnhe** [comment]
1. No, this is temporarily unachievable. All the type names have the same scope(`support.type.primitive.ts` here)

![demo2](https://user-images.githubusercontent.com/37491630/72488358-b34b9880-384b-11ea-9980-efaa76d08122.png)

2. The color name for `import` and `export` is "aqua"

**Comment by sainnhe** [comment]
At present I have thought of two sets of designs, one of which is the one just mentioned. You can try this design in branch `design1`, press `F5` and select the hard dark variant, then navigate a javascript project.

The downside of this design is that there is too much blue, which doesn't look very comfortable, especially in rust.

Another design is using yellow as string color just like what you suggested, and use blue as type name, use green as function name. You can try this branch in `design2`

![demo3](https://user-images.githubusercontent.com/37491630/72491136-180af100-3854-11ea-9533-5714fb0c2106.png)

The advantage of this design is that the mix of green and yellow looks great.

But the disadvantage is that someone may not accept yellow strings, especially in html, json and other files.

**Comment by sainnhe** [comment]
Btw, what I mean the border looks ugly is that after I tried the Material theme, and I found that many borders are not necessary and some can be replaced by shadow, so I think we can refer to its design.

![demo4](https://user-images.githubusercontent.com/37491630/72491606-869c7e80-3855-11ea-8e10-8242a0a02456.png)

What do you think about this?

**Comment by GulajavaMinistudio** [comment]
After checking design2 , i think i become a bit confused because string coloring in yellow and function color become green in HTML files. In JavaScript, there is good mixing, but string color is yellow.

Check this out 
![Screenshot_2020-01-16_15-49-34](https://user-images.githubusercontent.com/11639412/72508423-3551b680-3878-11ea-9326-cc0d32c961e8.png)
![Screenshot_2020-01-16_15-49-56](https://user-images.githubusercontent.com/11639412/72508441-3e428800-3878-11ea-8f56-fed19f921b92.png)


Maybe we should keep defining this. 
String color in green.
Boolean color in pink / purple.
Numeric color in red .

So it can differentiate when opening file with a lot of string and variables.

**Comment by GulajavaMinistudio** [comment]
And for coloring in Panel , Activity bar, Sidebar, Terminal, we can provide high contrast variant, alongside with bordered variant. 

Here's example for high contrast variant in material theme.
![Screenshot_2020-01-16_15-54-36](https://user-images.githubusercontent.com/11639412/72508756-d93b6200-3878-11ea-8a56-0b75578453bc.png)


What do you think about it ?

**Comment by sainnhe** [comment]
If we keep using green in string, then we are back to the point where the function name and the string cannot be distinguished.

Apologize for my previous remarks. I'm very sorry.

I think using yellow as string color and green as function color is the best solution currently. I have tried many other combinations, but this is the most suitable one.

The highlighting problem in html is easy to solve. We don't need to keep one syntax highlighting logic in every file types(this is actually exactly what the original gruvbox did). We can use green as string color in html/xml/json/yaml, etc.

I've optimized html, you can fetch `design2` and get it a try.

---

Designing a high contrast version sounds great!

I'm working on syntax highlighting recently. If you can, could you try to design a high contrast variant?

I know this may not be a easy job. If you are willing to design a high contrast version, here are the steps:

1. Refer to [vscode doc](https://code.visualstudio.com/api/references/theme-color) for workbench colors key.
2. Refer to [palette-dark.yml](https://github.com/gruvbox-material/gruvbox-material/blob/master/palette-dark.yml) and edit workbench colors in the [theme file](https://github.com/gruvbox-material/vscode/blob/17f789b502aa2ebad71c1030de784be29b64bca2/themes/gruvbox-material-medium-dark.json#L2197-L2490)

You can try to design a medium dark variant which uses `#282828` as normal background color, and use `#1d2021` as a darker high contrast color. I'll pick a high contrast color code for the hard dark variant later.

**Comment by GulajavaMinistudio** [comment]
I have design for dark variant with contrast color, with little border on it. A bit hard for choosing color for contrast, but i try to figure it out.

![Screenshot_2020-01-20_07-49-05](https://user-images.githubusercontent.com/11639412/72691694-fbbfca80-3b59-11ea-9673-dcb397d1bdba.png)

What do you think ?

I have pushed in branch design2 , and with the name "themes/gruvbox-material-hard-dark-contrast.json" . I named it  with suffix "-contrast" to differentiate with other color scheme in this folder.

**Comment by sainnhe** [comment]
It looks nice, great work!

I created 2 new branchs named `syntax` and `high-contrast`, so that we can develop these 2 features separately.

Some detailed designs may need to be discussed a bit more. I will try to finish the syntax highlighting in these two days, and let's develop the high contrast feature later.

**Comment by sainnhe** [comment]
The `syntax` branch has been merged, you can update this extension and get it a try.

---

For the high contrast variant, maybe we should remove the bordered variants and directly use the new high contrast workbench colors, because I think the bordered layout is really ugly 😂

I tried your design and I think this is the true modern design, it's absolutely better.

What do you think?

**Comment by sainnhe** [comment]
Hello, I adjusted some colors in the `Medium Dark High Contrast` variant based on your design, you can checkout the `high-contrast` branch and get it a try.

**Comment by GulajavaMinistudio** [comment]
It's ok and glad the design for high contrast is approved. Hehehe, so there is no bordered variant and just contrast variant ? I'm ok with that.

Ok i will pull and check this out.

**Comment by GulajavaMinistudio** [comment]
I think it's ok now, syntax coloring is good and balanced. I'm ok if you want to release with high contrast version in production too.


![Screenshot_2020-01-24_10-30-21](https://user-images.githubusercontent.com/11639412/73042775-06999880-3e95-11ea-858f-93a79f7ab8bd.png)

**Comment by sainnhe** [comment]
I'm working on the `ts` branch currently. In this branch, users can:

1. Select contrast(`hard`, `medium` and `soft`)
2. Select the workbench theme(`material`, `flat` and `high-contrast`)
3. Customize more configuration options(italicize comment, italicize keywords, etc)

I provided many configuration options in vim theme, and I'm going to do the same in vscode -- provide minimal necessary configuration options.

The flat workbench theme is inspired by onedark-pro, currently WIP

![onedark](https://user-images.githubusercontent.com/37491630/73043035-719b9d00-3e9e-11ea-8b26-220fc20d2039.png)

I'm going to release a new version after all of this has been finished.

Btw, are you familiar with typescript? If so, we can develop this branch together.

**Comment by sainnhe** [comment]
Microsoft has added your account to [publisher](https://marketplace.visualstudio.com/manage/publishers/sainnhe), you can now publish this extension independently.

**Comment by GulajavaMinistudio** [comment]
After i checking with TypeScript file, syntax coloring is good  as JavaScript style. You can check my screenshot above. TypeScript coloring follow JavaScript coloring as well. 

And for account publisher, i have check it, and i see gruvbox group publisher too.

**Comment by sainnhe** [comment]
The `ts` branch has been basically finished, but might still be buggy. Could you checkout `ts` and get it a try?

**Comment by sainnhe** [comment]
Several configuration options are provided, you can find them in user settings.

![demo](https://user-images.githubusercontent.com/37491630/73115319-4c229800-3f5f-11ea-8ea0-9c8a4c53b8e4.png)

**Comment by sainnhe** [comment]
Closed since v5.0.0 has been released.

In v5.0.0, the syntax highlighting is adjusted and 3 workbench styles are provided: `material`, `flat` and `highContrast`.

**Comment by sainnhe** [comment]
Hello, @GulajavaMinistudio I decided to delete this org because I found it's meanless.

Sorry for that but if you're still willing to maintain this project, please tell me and I'll add you to the collaborators of this repo.
